/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CoachesRouteImport } from './routes/coaches'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EliteAcademyRouteImport } from './routes/elite-academy'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as InternationalRouteImport } from './routes/international'
import { Route as SafeguardingRouteImport } from './routes/safeguarding'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StrengthConditioningRouteImport } from './routes/strength-conditioning'
import { Route as ApiIndoorInterestRouteImport } from './routes/api/indoor-interest'
import { Route as ProgrammesSlugRouteImport } from './routes/programmes/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesRoute = CoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EliteAcademyRoute = EliteAcademyRouteImport.update({
  id: '/elite-academy',
  path: '/elite-academy',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const InternationalRoute = InternationalRouteImport.update({
  id: '/international',
  path: '/international',
  getParentRoute: () => rootRouteImport,
} as any)
const SafeguardingRoute = SafeguardingRouteImport.update({
  id: '/safeguarding',
  path: '/safeguarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StrengthConditioningRoute = StrengthConditioningRouteImport.update({
  id: '/strength-conditioning',
  path: '/strength-conditioning',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIndoorInterestRoute = ApiIndoorInterestRouteImport.update({
  id: '/api/indoor-interest',
  path: '/api/indoor-interest',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesSlugRoute = ProgrammesSlugRouteImport.update({
  id: '/programmes/$slug',
  path: '/programmes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coaches': typeof CoachesRoute
  '/contact': typeof ContactRoute
  '/elite-academy': typeof EliteAcademyRoute
  '/founder': typeof FounderRoute
  '/international': typeof InternationalRoute
  '/safeguarding': typeof SafeguardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/strength-conditioning': typeof StrengthConditioningRoute
  '/api/indoor-interest': typeof ApiIndoorInterestRoute
  '/programmes/$slug': typeof ProgrammesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coaches': typeof CoachesRoute
  '/contact': typeof ContactRoute
  '/elite-academy': typeof EliteAcademyRoute
  '/founder': typeof FounderRoute
  '/international': typeof InternationalRoute
  '/safeguarding': typeof SafeguardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/strength-conditioning': typeof StrengthConditioningRoute
  '/api/indoor-interest': typeof ApiIndoorInterestRoute
  '/programmes/$slug': typeof ProgrammesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coaches': typeof CoachesRoute
  '/contact': typeof ContactRoute
  '/elite-academy': typeof EliteAcademyRoute
  '/founder': typeof FounderRoute
  '/international': typeof InternationalRoute
  '/safeguarding': typeof SafeguardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/strength-conditioning': typeof StrengthConditioningRoute
  '/api/indoor-interest': typeof ApiIndoorInterestRoute
  '/programmes/$slug': typeof ProgrammesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/coaches'
    | '/contact'
    | '/elite-academy'
    | '/founder'
    | '/international'
    | '/safeguarding'
    | '/sitemap.xml'
    | '/strength-conditioning'
    | '/api/indoor-interest'
    | '/programmes/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/coaches'
    | '/contact'
    | '/elite-academy'
    | '/founder'
    | '/international'
    | '/safeguarding'
    | '/sitemap.xml'
    | '/strength-conditioning'
    | '/api/indoor-interest'
    | '/programmes/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/coaches'
    | '/contact'
    | '/elite-academy'
    | '/founder'
    | '/international'
    | '/safeguarding'
    | '/sitemap.xml'
    | '/strength-conditioning'
    | '/api/indoor-interest'
    | '/programmes/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CoachesRoute: typeof CoachesRoute
  ContactRoute: typeof ContactRoute
  EliteAcademyRoute: typeof EliteAcademyRoute
  FounderRoute: typeof FounderRoute
  InternationalRoute: typeof InternationalRoute
  SafeguardingRoute: typeof SafeguardingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StrengthConditioningRoute: typeof StrengthConditioningRoute
  ApiIndoorInterestRoute: typeof ApiIndoorInterestRoute
  ProgrammesSlugRoute: typeof ProgrammesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches': {
      id: '/coaches'
      path: '/coaches'
      fullPath: '/coaches'
      preLoaderRoute: typeof CoachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elite-academy': {
      id: '/elite-academy'
      path: '/elite-academy'
      fullPath: '/elite-academy'
      preLoaderRoute: typeof EliteAcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/international': {
      id: '/international'
      path: '/international'
      fullPath: '/international'
      preLoaderRoute: typeof InternationalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safeguarding': {
      id: '/safeguarding'
      path: '/safeguarding'
      fullPath: '/safeguarding'
      preLoaderRoute: typeof SafeguardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strength-conditioning': {
      id: '/strength-conditioning'
      path: '/strength-conditioning'
      fullPath: '/strength-conditioning'
      preLoaderRoute: typeof StrengthConditioningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/indoor-interest': {
      id: '/api/indoor-interest'
      path: '/api/indoor-interest'
      fullPath: '/api/indoor-interest'
      preLoaderRoute: typeof ApiIndoorInterestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/$slug': {
      id: '/programmes/$slug'
      path: '/programmes/$slug'
      fullPath: '/programmes/$slug'
      preLoaderRoute: typeof ProgrammesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CoachesRoute: CoachesRoute,
  ContactRoute: ContactRoute,
  EliteAcademyRoute: EliteAcademyRoute,
  FounderRoute: FounderRoute,
  InternationalRoute: InternationalRoute,
  SafeguardingRoute: SafeguardingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StrengthConditioningRoute: StrengthConditioningRoute,
  ApiIndoorInterestRoute: ApiIndoorInterestRoute,
  ProgrammesSlugRoute: ProgrammesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
